name: Build and Push to ECR
 
on:
  push:
    branches:
      - main
 
env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: test-project  #ECRリポジトリ名を指定
 
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # OIDCトークン取得のため
      contents: read    # リポジトリのコードを読み取るため
 
    steps:
      - name: Checkout repository # ソースコードを取得
        uses: actions/checkout@v4 
 
      - name: Configure AWS credentials # AWS認証情報の設定
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          role-to-assume: arn:aws:iam::992382612474:role/github-actions-ecr-push-example-role
          aws-region: ap-northeast-1

    # これを使うだけで docker login コマンドが不要になります
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

    # イメージのビルド・タグ付け・プッシュを一括で行う
    # 1. ECRへプッシュ
      - name: Build and Push
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # 次のステップにイメージの場所を伝える
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # 2. 既存のタスク定義をAWSから取得してファイルにする
      - name: Download task definition
        run: |
          # test-project の部分はご自身の「タスク定義ファミリー名」に変えてください
          aws ecs describe-task-definition --task-definition test-project --query taskDefinition > task-definition.json

      # 3. ファイル内の「イメージ名」を最新のものに書き換える
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: app # CloudFormationで決めたコンテナ名
          image: ${{ steps.build-image.outputs.image }}

      # 4. ECSサービスを更新（デプロイ）
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: test-project-service  # CloudFormationで作成したサービス名
          cluster: test-project  # CloudFormationで作成したクラスター名
          wait-for-service-stability: true